version: 2.1

executors:
  mongoruby:
    docker:
      - image: cimg/ruby:3.3.12
      - image: mongo:5.0.12

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.5.1

jobs:
  test-job:
    executor: mongoruby
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: gem install bundler && bundle install
      - run:
          name: Run tests
          command: |
            TEST_FILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split)
            bundle exec rspec --format RspecJunitFormatter -o test/reports/rspec.xml - ${TEST_FILES}
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports/rspec.xml
          destination: rspec.xml
  lint-job:
    executor: mongoruby
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: gem install bundler && bundle install
      - run:
          name: Run lint
          command: bundle exec rubocop controllers/ models/ constants/ exceptions/
workflows:
  version: 2.1
  build:
    jobs:
      - test-job
      - lint-job